In [190]:
from collections import Counter
import pandas as pd
import numpy as np

In [7]:
r1=['My nickname is ft.jgt','Someone is going to my place']

In [4]:
Counter(" ".join(r1).split(" ")).items()

[('Someone', 1),
 ('ft.jgt', 1),
 ('My', 1),
 ('is', 2),
 ('to', 1),
 ('going', 1),
 ('place', 1),
 ('my', 1),
 ('nickname', 1)]

In [16]:
df= pd.DataFrame(r1,columns=['text'])
results = set()
result = df['text'].str.lower().str.split().apply(results.update)
print(results)

set(['someone', 'ft.jgt', 'my', 'is', 'to', 'going', 'place', 'nickname'])


In [18]:
result = Counter(" ".join(df['text'].values.tolist()).split(" ")).items()


In [84]:
text = pd.read_csv("../TextCorpus/Fiction/LeoTolstoy_WarAndPeace.txt",delimiter="\n",quoting=3)

In [48]:
text[0:1]



0  The Project Gutenberg EBook of War and Peace, ...

In [51]:
text.columns.values

array(['\xef\xbb\xbf'], dtype=object)

In [54]:
text[0:1]


0  The Project Gutenberg EBook of War and Peace, ...

In [101]:
import string

ma         = text.as_matrix()[:,0]
dictionary = set()
freq       = dict()

for line in ma:
    words = [ x.lower() for x in line.split() ] 
    for word in words:
        word = word.translate(string.maketrans("",""), string.punctuation)
        if word in dictionary:
            freq[word] += 1
        else:
            freq[word] = 1
            dictionary.add(word)

In [102]:
freq

{'': 295,
 'raining': 3,
 'divinely': 1,
 'hordes': 1,
 'nunnery': 3,
 'inadequacy': 1,
 'colony': 2,
 'retain': 7,
 'delivering': 2,
 'yellow': 17,
 'four': 103,
 'prices': 3,
 'woods': 9,
 'gnarled': 3,
 'hanging': 32,
 'army\xe2\x80\x94napoleon': 1,
 'mouth\xe2\x80\x94seemed': 1,
 'worst\xe2\x80\x94road': 1,
 'thorn': 1,
 'aggression': 2,
 'briskness': 3,
 'looking': 391,
 'russia\xe2\x80\x94and': 2,
 'granting': 1,
 'eligible': 1,
 'electricity': 6,
 'rupture': 7,
 'hosjeradek': 2,
 'unanswered': 1,
 'wheeled': 2,
 'lency': 1,
 'superficially': 1,
 'wholeheartedly': 1,
 'officer\xe2\x80\x94comes': 1,
 'lord': 52,
 'meadows': 6,
 'shaving': 3,
 'sinking': 16,
 'courtmartial': 3,
 'shielding': 1,
 'titi': 4,
 'peasants\xe2\x80\x94even': 1,
 'grenadiers': 8,
 'bile': 2,
 'powders': 3,
 'deputation': 9,
 'forties': 1,
 'rearguard': 10,
 'leisurely': 6,
 'queerlooking': 1,
 'fullblooded': 1,
 'stabbed': 1,
 'bringing': 23,
 'ruinous': 4,
 'prizing': 1,
 'revelers': 1,
 'disturb': 6,
 'r

In [110]:
threshold = 5
for key, value in sorted(freq.iteritems(), key=lambda (k,v): (v,k)):
    if value >= threshold: 
        print "%s: %s" % (key, value)

1808: 5
1e1: 5
30: 5
5: 5
abreast: 5
absent: 5
abused: 5
accident: 5
accuracy: 5
accurately: 5
achievement: 5
acknowledged: 5
addition: 5
adieu: 5
admiring: 5
adroit: 5
afforded: 5
afterdinner: 5
aime: 5
aiming: 5
alleged: 5
alluded: 5
ambulance: 5
anecdotes: 5
angina: 5
antechamber: 5
anticipated: 5
ants: 5
apartment: 5
applicable: 5
appointments: 5
apráksina: 5
apt: 5
arakcheevs: 5
arbitrarily: 5
ascertain: 5
aspect: 5
astray: 5
atone: 5
attracting: 5
attribute: 5
augesd: 5
authors: 5
awarded: 5
banners: 5
banquet: 5
bar: 5
bared: 5
barefooted: 5
barrels: 5
bathed: 5
bayonet: 5
bazaar: 5
bazdeev: 5
bearers: 5
bears: 5
beaver: 5
behaving: 5
belliard: 5
belongs: 5
bend: 5
betray: 5
bewilderment: 5
bewitching: 5
birth: 5
bivouacking: 5
blackened: 5
blackguards: 5
blandly: 5
blinking: 5
block: 5
blockhead: 5
bloodshot: 5
bluish: 5
boats: 5
bobtailed: 5
bodice: 5
bored: 5
boundary: 5
branch: 5
bravest: 5
brightness: 5
brings: 5
brood: 5
brook: 5
brush: 5
buckwheat: 5
buried: 5
bursting: 5

In [96]:
tst.add("D")

In [99]:
import string
s = "string. With. Punctuation?" # Sample string 
out = s.translate(string.maketrans("",""), string.punctuation)

In [100]:
out

'string With Punctuation'

In [112]:
(3,2).add


AttributeError: 'tuple' object has no attribute 'add'

In [202]:

a = np.zeros(shape=(0,0))

a.shape

(0, 0)

In [204]:
a = np.vstack([a,[3]])
a

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [152]:
"Hey294rjifjds fijOIJDFOIJ".encode("BIN")

LookupError: unknown encoding: BIN

In [159]:
v = np.matrix("[1 2; 3 4]")

In [160]:
v


matrix([[1, 2],
        [3, 4]])

In [155]:
v / 2

matrix([[0, 1],
        [1, 2]])

In [156]:
v[,1]

SyntaxError: invalid syntax (<ipython-input-156-b44626f1a8c1>, line 1)

In [164]:
v[:,0] * 3

matrix([[3],
        [9]])

In [165]:
v

matrix([[1, 2],
        [3, 4]])

In [166]:
v.fill(3)

In [167]:
v



matrix([[3, 3],
        [3, 3]])

In [183]:
v[0:2,1]

matrix([[3],
        [3]])

In [184]:
a = set([1,2,3]
       )

In [185]:
len(a)


3

In [186]:
np.zeros(shape=(0,2))

array([], shape=(0, 2), dtype=float64)

In [192]:
a = np.zeros(shape=(0,0))

In [194]:
a

array([], shape=(0, 0), dtype=float64)

In [195]:
a = np.vstack[ [a,[1]] ]

TypeError: 'function' object has no attribute '__getitem__'

In [205]:
a = [[1,2,3],[4,5,6],[7,8,9]]

In [206]:
a

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [207]:
[ x.join() for x in a ]

AttributeError: 'list' object has no attribute 'join'

In [208]:
[ " ".join() for x in a ]

TypeError: join() takes exactly one argument (0 given)

In [209]:
[ " ".join(x) for x in a ]

TypeError: sequence item 0: expected string, int found

In [212]:
nl = []
[ nl.append(x) for x in a ]

[None, None, None]

In [214]:
[] + [1,2,3] +[4,5]

[1, 2, 3, 4, 5]

In [217]:
b = dict()
b["D"] = 1

In [219]:
"D" in b.keys()

True

In [220]:
a = [1,2,3,4,5]

for i in a:
    for z in a:
        print(i,z)

(1, 1)
(1, 2)
(1, 3)
(1, 4)
(1, 5)
(2, 1)
(2, 2)
(2, 3)
(2, 4)
(2, 5)
(3, 1)
(3, 2)
(3, 3)
(3, 4)
(3, 5)
(4, 1)
(4, 2)
(4, 3)
(4, 4)
(4, 5)
(5, 1)
(5, 2)
(5, 3)
(5, 4)
(5, 5)


In [224]:
a = [1,3]
b = a.copy
b[0] = 2

AttributeError: 'list' object has no attribute 'copy'

In [222]:
a

[2, 3]

In [223]:
b

[2, 3]

In [226]:
a = range(1,4)

In [227]:
a

[1, 2, 3]

In [228]:
a.pop()

3

In [229]:
a


[1, 2]

In [230]:
a.pop(0)

1

In [236]:

for i in range(10,2000,100):
    segment = range(i)
    segRange = range(len(segment))
    itterSize = 0
    itterSize2 = 0
    for word1 in segment:
        for word2Loc in segRange:
            itterSize += 1
        segRange.pop(0)

    for word1 in segment:
        for word2Loc in segment:
            itterSize2 += 1

    print(itterSize,"Versus Stupido",itterSize2, "DIFF:",(itterSize2-itterSize))

(55, 'Versus Stupido', 100, 'DIFF:', 45)
(6105, 'Versus Stupido', 12100, 'DIFF:', 5995)
(22155, 'Versus Stupido', 44100, 'DIFF:', 21945)
(48205, 'Versus Stupido', 96100, 'DIFF:', 47895)
(84255, 'Versus Stupido', 168100, 'DIFF:', 83845)
(130305, 'Versus Stupido', 260100, 'DIFF:', 129795)
(186355, 'Versus Stupido', 372100, 'DIFF:', 185745)
(252405, 'Versus Stupido', 504100, 'DIFF:', 251695)
(328455, 'Versus Stupido', 656100, 'DIFF:', 327645)
(414505, 'Versus Stupido', 828100, 'DIFF:', 413595)
(510555, 'Versus Stupido', 1020100, 'DIFF:', 509545)
(616605, 'Versus Stupido', 1232100, 'DIFF:', 615495)
(732655, 'Versus Stupido', 1464100, 'DIFF:', 731445)
(858705, 'Versus Stupido', 1716100, 'DIFF:', 857395)
(994755, 'Versus Stupido', 1988100, 'DIFF:', 993345)
(1140805, 'Versus Stupido', 2280100, 'DIFF:', 1139295)
(1296855, 'Versus Stupido', 2592100, 'DIFF:', 1295245)
(1462905, 'Versus Stupido', 2924100, 'DIFF:', 1461195)
(1638955, 'Versus Stupido', 3276100, 'DIFF:', 1637145)
(1825005, 'Versus S

In [238]:
segment = range(10)
segRange = range(len(segment))
itterSize = 0
itterSize2 = 0
for word1 in segment:
    for word2Loc in segRange:
        print(word1,segment[word2Loc])
    segRange.pop(0)

(0, 0)
(0, 1)
(0, 2)
(0, 3)
(0, 4)
(0, 5)
(0, 6)
(0, 7)
(0, 8)
(0, 9)
(1, 1)
(1, 2)
(1, 3)
(1, 4)
(1, 5)
(1, 6)
(1, 7)
(1, 8)
(1, 9)
(2, 2)
(2, 3)
(2, 4)
(2, 5)
(2, 6)
(2, 7)
(2, 8)
(2, 9)
(3, 3)
(3, 4)
(3, 5)
(3, 6)
(3, 7)
(3, 8)
(3, 9)
(4, 4)
(4, 5)
(4, 6)
(4, 7)
(4, 8)
(4, 9)
(5, 5)
(5, 6)
(5, 7)
(5, 8)
(5, 9)
(6, 6)
(6, 7)
(6, 8)
(6, 9)
(7, 7)
(7, 8)
(7, 9)
(8, 8)
(8, 9)
(9, 9)


In [ ]:
dictList = []
for key, value in sorted(wordIndex.iteritems(), key=lambda (k, v): (v, k)):
    dictList.append(key)

In [239]:
dictionary

{'',
 'raining',
 'divinely',
 'hordes',
 'nunnery',
 'inadequacy',
 'colony',
 'retain',
 'delivering',
 'yellow',
 'four',
 'prices',
 'woods',
 'gnarled',
 'hanging',
 'army\xe2\x80\x94napoleon',
 'mouth\xe2\x80\x94seemed',
 'worst\xe2\x80\x94road',
 'thorn',
 'aggression',
 'briskness',
 'looking',
 'russia\xe2\x80\x94and',
 'granting',
 'eligible',
 'electricity',
 'rupture',
 'hosjeradek',
 'unanswered',
 'wheeled',
 'lency',
 'superficially',
 'wholeheartedly',
 'officer\xe2\x80\x94comes',
 'lord',
 'meadows',
 'shaving',
 'sinking',
 'courtmartial',
 'shielding',
 'titi',
 'peasants\xe2\x80\x94even',
 'grenadiers',
 'bile',
 'powders',
 'deputation',
 'forties',
 'rearguard',
 'leisurely',
 'queerlooking',
 'fullblooded',
 'stabbed',
 'bringing',
 'ruinous',
 'prizing',
 'revelers',
 'disturb',
 'recollections',
 'uttering',
 'prize',
 's\xc3\xb3oonya',
 'wooden',
 'notion\xe2\x80\x94science',
 'deity\xe2\x80\x94the',
 'wednesday',
 'oooo',
 'implanting',
 'persisted',
 'cassoc

In [243]:
a = set()
a.add( (1,2) )

In [245]:
(2,1) in a

False

In [246]:
a = set([2,3,4])

In [247]:
b = a

In [248]:
a.pop()

2

In [249]:
a

{3, 4}

In [250]:
b

{3, 4}

In [251]:
b


{3, 4}

In [252]:
b.remove(3)

In [253]:
b

{4}